#ifndef MESH_CONFIG_PROV_H__
#define MESH_CONFIG_PROV_H__


#ifndef MESH_PROV_LINK_TIMEOUT_MIN_US
#define MESH_PROV_LINK_TIMEOUT_MIN_US 60000000
#endif



#ifndef MESH_FEATURE_PB_ADV_ENABLED
#define MESH_FEATURE_PB_ADV_ENABLED 1
#endif

#ifndef MESH_FEATURE_PB_GATT_ENABLED
#define MESH_FEATURE_PB_GATT_ENABLED 0
#endif

#ifndef MESH_PROV_BEARER_ADV_UNPROV_BEACON_INTERVAL_MS
#define MESH_PROV_BEARER_ADV_UNPROV_BEACON_INTERVAL_MS 2000
#endif

#ifndef MESH_PROV_BEARER_GATT_UNPROV_BEACON_INTERVAL_MS
#define MESH_PROV_BEARER_GATT_UNPROV_BEACON_INTERVAL_MS 200
#endif

#ifndef MESH_PROV_BEARER_ADV_TX_BUFFER_SIZE
#define MESH_PROV_BEARER_ADV_TX_BUFFER_SIZE  128
#endif


#ifndef MESH_PROV_FORCE_SECURE_PROVISIONING
#define MESH_PROV_FORCE_SECURE_PROVISIONING (0)
#endif


#endif
