#ifndef MESH_DEFINES_H__
#define MESH_DEFINES_H__



#define BEARER_ACCESS_ADDR_NONCONN 0x8E89BED6U
#define MESH_SEG_PAYLOAD_SIZE_MAX (380)
#define MESH_UPPER_TRANSPORT_PDU_SIZE_MAX (384)
#define MESH_UNSEG_PAYLOAD_SIZE_MAX (11)
#define MESH_ADV_CHAN_ALL {37, 38, 39}
#define MESH_ADV_CHAN_DEFAULT MESH_ADV_CHAN_ALL
#define MESH_KEY_SIZE  (16)
#define MESH_NETID_SIZE (8)
#define MESH_UUID_SIZE (16)
#define MESH_TTL_BIT_COUNT (7)
#define MESH_TTL_MAX ((1 << MESH_TTL_BIT_COUNT) - 1)
#define MESH_GLOBAL_KEY_INDEX_MAX  (0xFFF)
#define MESH_BEACON_SECURE_NET_BCAST_INTERVAL_SECONDS 10
#define MESH_BEACON_OBSERVATION_PERIODS 2
#define MESH_BEACON_UNPROV_URI_HASH_SIZE    (4)
#define MESH_ECDH_PUBLIC_KEY_SIZE    (64)
#define MESH_ECDH_PRIVATE_KEY_SIZE   (32)
#define MESH_ECDH_SHARED_SECRET_SIZE    (32)

#define MESH_ADDR_UNASSIGNED                  (0x0000)
#define MESH_ALL_PROXIES_ADDR                 (0xFFFC)
#define MESH_ALL_FRIENDS_ADDR                 (0xFFFD)
#define MESH_ALL_RELAYS_ADDR                  (0xFFFE)
#define MESH_ALL_NODES_ADDR                   (0xFFFF)
#define MESH_ADDR_TYPE_BITS_OFFSET            (14)
#define MESH_ADDR_TYPE_BITS_MASK              (0xC000)
#define MESH_IRQ_PRIORITY_THREAD              (15)
#define MESH_IRQ_PRIORITY_LOWEST              (4)

#define NETWORK_SEQNUM_BITS         24
#define NETWORK_SEQNUM_MAX          ((1 << NETWORK_SEQNUM_BITS) - 1)
#define NETWORK_RELAY_RETRANSMITS_MAX   ((1 << 3) - 1)
#define NETWORK_RELAY_INTERVAL_STEPS_MAX ((1 << 5) - 1)
#define NETWORK_RELAY_INTERVAL_MAX_MS (NETWORK_RELAY_INTERVAL_STEPS_MAX * 10)
#define NETWORK_MIN_IV_UPDATE_INTERVAL_MINUTES (96 * 60)
#define NETWORK_IV_RECOVERY_LIMIT 42
#define NETWORK_BEARER BEARER_ADV_RADIO

#define TRANSPORT_SAR_RX_TIMEOUT_MIN                            MS_TO_US(10000)
#define TRANSPORT_SAR_RX_TIMEOUT_MAX                            MS_TO_US(120000)
#define TRANSPORT_SAR_RX_ACK_TIMEOUT_BASE_MIN                   MS_TO_US(150)
#define TRANSPORT_SAR_RX_ACK_TIMEOUT_BASE_MAX                   MS_TO_US(10000)
#define TRANSPORT_SAR_RX_ACK_TIMEOUT_PER_HOP_ADDITION_MIN       MS_TO_US(50)
#define TRANSPORT_SAR_RX_ACK_TIMEOUT_PER_HOP_ADDITION_MAX       MS_TO_US(10000)
#define TRANSPORT_SAR_TX_RETRY_TIMEOUT_BASE_MIN                 MS_TO_US(200)
#define TRANSPORT_SAR_TX_RETRY_TIMEOUT_BASE_MAX                 MS_TO_US(10000)
#define TRANSPORT_SAR_TX_RETRY_TIMEOUT_PER_HOP_ADDITION_MIN     MS_TO_US(200)
#define TRANSPORT_SAR_TX_RETRY_TIMEOUT_PER_HOP_ADDITION_MAX     MS_TO_US(10000)
#define TRANSPORT_SAR_TX_TIMEOUT_MIN                            MS_TO_US(150)
#define TRANSPORT_SAR_TX_TIMEOUT_MAX                            MS_TO_US(60000)
#define TRANSPORT_SAR_TX_RETRIES_MIN                            (2)
#define TRANSPORT_SAR_TX_RETRIES_MAX                            (255)
#define TRANSPORT_SAR_SEQNUM_DIFF_MAX                           (8191)

#define HEARTBEAT_TRIGGER_TYPE_RELAY    0x0001
#define HEARTBEAT_TRIGGER_TYPE_PROXY    0x0002
#define HEARTBEAT_TRIGGER_TYPE_FRIEND   0x0004
#define HEARTBEAT_TRIGGER_TYPE_LPN      0x0008
#define HEARTBEAT_TRIGGER_TYPE_RFU_MASK 0x000F


#endif  /* MESH_DEFINES_H__ */
