#ifndef BEARER_DEFINES_H__
#define BEARER_DEFINES_H__


#define BEARER_ACCESS_ADDR_NONCONN 0x8E89BED6U
#define BEARER_ADV_INT_MIN_MS (20)
#define BEARER_ADV_INT_MAX_MS (10240)
#define BEARER_SCAN_WIN_MIN_MS (3)
#define BEARER_SCAN_INT_MAX_MS (40960)
#define BEARER_HFCLK_DRIFT_PPM_MAX  (50)


#endif  /* BEARER_DEFINES_H__ */
